### ISSUE TITLE
使用colab导出后，评论过的条目评论内容消失或错乱

### ISSUE THREAD

**Issue by SomiaWhiteRing** [jerrylususu/bangumi-takeout-py#5]
数据源采用Bangumi Archive
[导出的takeout.json与html.zip](https://github.com/jerrylususu/bangumi-takeout-py/files/8660657/takeout.zip)

**Comment by SomiaWhiteRing** [comment]
试了一下 用bangumiAPI也是一样的效果 应该不是数据源的问题……

**Comment by jerrylususu** [comment]
我正在检查相关文件。可以提供一些示例吗？例如具体是哪个条目有问题？

**Comment by jerrylususu** [comment]
看起来有一个评论是「精雕细琢的艺术品。除了实在是太短了完全玩不尽兴之外可谓臻于完美的佳作。摆出一副后事留到续作再讲的架势然后就再也没有续作了实在是……」，这条评论似乎出现在了多个位置。目前看来似乎在 `takeout.json` 中这个问题就已经存在了，大概率是 `fetch.py` 中的问题。然而在没有 token 的情况下我很难调试这个问题。稍后我会用 Bangumi 的站内信与您取得联系。

**Comment by SomiaWhiteRing** [comment]
> 我正在检查相关文件。可以提供一些示例吗？例如具体是哪个条目有问题？
全部comment不为null的条目都出了问题bgm38
有内容的comment除了空白就是"不思议的时间杀手，玩起来就停不下来""先打了海猫再回来补寒蝉，相比之下少了些炫技更像是本格的推理剧，但也因此有着独一无二的顺畅感。能够让人满足的出题篇。"之类的特定评论复读

**Comment by jerrylususu** [comment]
啊，抱歉，突然发现 `token` 可能不是必须的。可以将程序执行目录中的 `collections.json` 上传吗？这个文件就是用 `token` 获取用户信息后的结果。（太久没维护忘了 ）

**Comment by SomiaWhiteRing** [comment]
> 啊，抱歉，突然发现 `token` 可能不是必须的。可以将程序执行目录中的 `collections.json` 上传吗？这个文件就是用 `token` 获取用户信息后的结果。（太久没维护忘了 ）

正因为colab没法下载token的报错查的焦头烂额……
用不到的话就简单了

[collections.zip](https://github.com/jerrylususu/bangumi-takeout-py/files/8661087/collections.zip)

**Comment by jerrylususu** [comment]
问题有些诡异... `collections.json` 是直接用从 Bangumi API 获取的分页收藏数据拼接而成的，但是似乎 comment 重复在这里就已经出现了。初步怀疑可能是上游 Bangumi API 的问题，但是可能还是需要 `access_token` 才能进一步确认。如果用的是 colab 的话，这里的 `token` 就是点击认证链接后的 `access_token`。有安全顾虑的话可以走站内信发给我。

**Comment by SomiaWhiteRing** [comment]
> 问题有些诡异... `collections.json` 是直接用从 Bangumi API 获取的分页收藏数据拼接而成的，但是似乎 comment 重复在这里就已经出现了。初步怀疑可能是上游 Bangumi API 的问题，但是可能还是需要 `access_token` 才能进一步确认。如果用的是 colab 的话，这里的 `token` 就是点击认证链接后的 `access_token`。有安全顾虑的话可以走站内信发给我。

通过站内信发送了。

**Comment by jerrylususu** [comment]
应该是上游 API 问题。我自己的账户也出现了相同问题 😂
会尝试向 Bangumi API 维护者反馈。

**Comment by jerrylususu** [comment]
上游已经修复。我用自己的账户测试，已经恢复正常。 @SomiaWhiteRing 可以现在再重新试试？

**Comment by SomiaWhiteRing** [comment]
> 上游已经修复。我用自己的账户测试，已经恢复正常。 @SomiaWhiteRing 可以现在再重新试试？

我这边也没问题 可以close了😆
